## TASK - Applications of Numpy

### Import Necessary Functions

In [1]:
#Import Numpy

import numpy as np

### Numpy Array Initialization

In [2]:
#Initializing a Numpy Array

arr = np.array([15,22,30,46,57,62,71,88,94])
print("Numpy Array: \n", arr)

Numpy Array: 
 [15 22 30 46 57 62 71 88 94]


### Basic Operations

In [3]:
print("Shape of the Numpy Array: ", arr.shape)
print()
print("Dimension of the Numpy Array: ", arr.ndim)

Shape of the Numpy Array:  (9,)

Dimension of the Numpy Array:  1


### Indexing

In [4]:
#Positive Indexing
print("Indexing from Left to Right of the Array: ", arr[0], arr[5])

Indexing from Left to Right of the Array:  15 62


In [5]:
#Negative Indexing
print("Negative Indexing: ", arr[-1], arr[-7])

Negative Indexing:  94 30


In [6]:
#Mathematical Operations on Indices
print("Indexing Mathematical Operations (Addition, Subtraction, Multiplication, Division): ", arr[0]+arr[2], arr[4]-arr[2], arr[4]*arr[7], arr[8]/arr[5])

Indexing Mathematical Operations (Addition, Subtraction, Multiplication, Division):  45 27 5016 1.5161290322580645


### Slicing

In [7]:
# Slicing
print("Slicing: ", arr[2:6])

Slicing:  [30 46 57 62]


In [8]:
# Slicing
print("Slicing: ", arr[::-2])

Slicing:  [94 71 57 30 15]


In [9]:
# Slicing
print("Slicing: ", arr[:-2])

Slicing:  [15 22 30 46 57 62 71]


### Reshaping the Array

In [10]:
arr1 = arr.reshape(3, 3)
print("Reshaped Array:", arr1)

Reshaped Array: [[15 22 30]
 [46 57 62]
 [71 88 94]]


### Iterating over the Numpy Array

In [11]:
for i in arr1:
  print(i)

[15 22 30]
[46 57 62]
[71 88 94]
